[project]
name = "pyboneco"
version = "0.1.0"
description = "Basic library for working with Boneco devices"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bleak==0.22.3",
    "bleak-retry-connector==3.6.0",
    "cryptography==44.0.0",
]
